name: template
on: push
jobs:
  build:
     runs-on: windows-latest
     steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          auto-activate-base: true
      - run: test
